apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepstudy-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deepstudy-ai
  template:
    metadata:
      labels:
        app: deepstudy-ai
    spec:
      containers:
      - name: deepstudy-ai
        image: deepstudy-ai:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000 