name: Continuous Integration
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          pytest --cov=backend tests/
          
      - name: Run security checks
        run: |
          bandit -r backend/
          safety check
          
      - name: Build Docker image
        run: |
          docker build -t deepstudy-ai .
          
      - name: Run container tests
        run: |
          docker run deepstudy-ai pytest 